version: '3.8'

services:
  yii2:
    image: duggana1994/yii2-app:latest
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
