version: '3.8'

services:
  yii2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: yii2-app
    container_name: yii2-app
    volumes:
      - .:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/yii2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2
