- hosts: ec2-instance
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy NGINX config
      copy:
        src: ../nginx/yii2.conf
        dest: /etc/nginx/sites-available/yii2
        mode: '0644'

    - name: Enable NGINX config
      file:
        src: /etc/nginx/sites-available/yii2
        dest: /etc/nginx/sites-enabled/yii2
        state: link
        force: yes

    - name: Remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded

    - name: Initialize Docker Swarm
      shell: docker swarm init || true

    - name: Deploy Docker stack
      shell: docker stack deploy -c /home/ubuntu/app/docker-stack.yml yii2app
