name: Deploy Yii2 to Docker Swarm

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

    - name: Install Ansible and jq
      run: |
        sudo apt update
        sudo apt install -y ansible jq

    - name: Set up SSH for Ansible
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook playbooks/setup.yml
    

