name: Deploy Yii2 to Docker Swarm

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        cd docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

    - name: SSH and Update Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker service rm yii2 || true
          docker service create \
            --name yii2 \
            --publish published=9000,target=9000 \
            --replicas=1 \
            ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
